### ISSUE TITLE
Add strand bias estimated using Fisher's Exact Test

### ISSUE THREAD

**Issue by mfoll** [IARCbioinfo/needlestack#107]
Like in [GATK](https://www.broadinstitute.org/gatk/guide/tooldocs/org_broadinstitute_gatk_tools_walkers_annotator_FisherStrand.php)

**Comment by mfoll** [comment]
Put it per sample (FORMAT field) and also for the whole variant (INFO field)

**Comment by mfoll** [comment]
Old version commented exists in the code but needs to be vectorised, checked for NAs and offer the option to hard filter on it like RVSB and SOR.

**Comment by tdelhomme** [comment]
Code [ok](https://github.com/IARCbioinfo/needlestack/commit/5a385e1c22de538bc0f287febdc3348fed726f36) but remaining to add a default threshold and add it to the documentation
