### ISSUE TITLE
plot improved error rate confidence interval 

### ISSUE THREAD

**Issue by tdelhomme** [IARCbioinfo/needlestack#117]
Plot a better estimated confidence interval (0.01, 0.99) according to the data.
At this time, we compute only the confidence interval for the maximum coverage with `qnbinom()`, and plot a line from 0 to this value (see big blue dotted lines on the following plot).
The issue is that the shape of this interval is not necessary linear.
Now we would like to compute this confidence interval for a sufficient number of points to be sufficiently accurate. Let's take 1000 equidistant points in {0,max(coverage)} if max(coverage)>1000, otherwise all coverage between 0 and the maximum coverage.

![chr17_7572907_7572907_g_c](https://cloud.githubusercontent.com/assets/13535602/15008269/62bf4560-11df-11e6-940f-05797d56e575.png)

Use this opportunity to change colors for error rate and confidence interval from blue to black to erase conflict with the contour for qvalue=10.

**Comment by tdelhomme** [comment]
why minor bug?

**Comment by tdelhomme** [comment]
I guessed "bug" was only for pipeline crashing...

**Comment by mfoll** [comment]
The current line is wrong, so it's a bug. It's still minor as it's only visual.
