### ISSUE TITLE
Multiple tumors should be able to share the same matched normal

### ISSUE THREAD

**Issue by mfoll** [IARCbioinfo/needlestack#153]
This is a common experiment design:
* biological replicates
* technical replicates
* multiple regions of a tumor sequenced
* temporal sequencing of the same tumor
etc.
Currently it is crashing in `needlestack.r` because [these lines](https://github.com/IARCbioinfo/needlestack/blob/master/bin/needlestack.r#L118-L119) return vectors instead of a single numerical value:
```R
Tindex = sapply( 1:nrow(TNpairs.complete) , function(k) return(which(indiv_run[,2]==TNpairs.complete$TUMOR[k])) )
Nindex = sapply( 1:nrow(TNpairs.complete) , function(k) return(which(indiv_run[,2]==TNpairs.complete$NORMAL[k])) )
```
The problem is that it interferes with the `GERMLINE` status as a normal will have multiple tumor. I propose in this case to simply take the first one to assign the status. Similarly, if someone decide to put multiple normal for the same tumor we can simply take the first one. In practice I think only adding `[1]` after the two `which(...)` above would do the trick.

**Comment by mfoll** [comment]
@nalcala what do you think? do you see something I am missing?

**Comment by tdelhomme** [comment]
@nalcala Was this fixed?

**Comment by tdelhomme** [comment]
don't think, maybe we can shifted to next version.

**Comment by mfoll** [comment]
I think I remember this was actually already possible and no change was needed
