### ISSUE TITLE
Feature: Consider realignment using freebayes/glia/???

### ISSUE THREAD

**Issue by mmterpstra** [IARCbioinfo/needlestack#158]
Freebayes and the GATK Haplotypecaller perform internal (indel- /  left-) realignment over the called samples to improve the calling accuracy / consistency. Consider including this in the workflow or add suggestions to perform this.

**Comment by mfoll** [comment]
Thanks for the suggestion. We are using [ABRA](https://github.com/mozack/abra) for this purpose (and we have a [nextflow pipeline](https://github.com/IARCbioinfo/abra-nf) for this too). For modularity reasons we prefer to keep this step out of the needlestack pipeline itself, but you are right, this is something we should add in the documentation (on top of many other things actually)... 
Do you think this would solve your issue?

**Comment by mmterpstra** [comment]
Yes maybe add it in the in the manual also
> - A set of [BAM files](https://samtools.github.io/hts-specs/) (called `*.bam`) grouped in a single folder along with their [index files](http://www.htslib.org/doc/samtools.html) (called `*.bam.bai`). A minimum of 20 BAM files is recommended. 


to 


 > - A set of [BAM files](https://samtools.github.io/hts-specs/) (called \`*.bam\`) grouped in a single folder along with their [index files](http://www.htslib.org/doc/samtools.html) (called `*.bam.bai`). A minimum of 20 BAM files is recommended. Advised it to perform realingment with [GATK IndelRealigner](https://software.broadinstitute.org/gatk/guide/tooldocs/org_broadinstitute_gatk_tools_walkers_indels_IndelRealigner.php) or [ABRA2](https://github.com/mozack/abra2)
