### ISSUE TITLE
Github readme != Docker readme

### ISSUE THREAD

**Issue by mmterpstra** [IARCbioinfo/needlestack#159]
Check if they are the same and fix if needed.

#### example
Docker says

> ### Nextflow and Docker
> If you can't install docker or don't want to use it, the pipeline will also work if you install bedtools, samtools, Rscript from R and g++ compiler to compile the file mpileup2readcounts.cc, put them in your path (executables are assumed to be respectively called bedtools, samtools, Rscript and mpileup2readcounts). In this case, remove the -with-docker option from step 5 above.

Github says 

> ### Nextflow and Docker
> If you can't install docker or don't want to use it, the pipeline will also work if you install perl, bedtools, samtools and Rscript from R and put them in your path (executables are assumed to be respectively called perl, bedtools, samtools and Rscript). In this case, remove the -with-docker option from step 5 above.

**Comment by tdelhomme** [comment]
@mmterpstra You're right, but actually these readmes are not based on the same GitHub branch. 
Docker is based on current dev branch but GitHub is based on the revised branch (master).
When we will push, this sould be synchronized.

**Comment by mfoll** [comment]
Docker Hub is automatically displaying the README file from the last GitHub branch built. I agree this is an undesirable behaviour but there is nothing we can do about it currently.
