### ISSUE TITLE
add extra robust regression parameters

### ISSUE THREAD

**Issue by tdelhomme** [IARCbioinfo/needlestack#162]
We have an option `extra_robust_gl`, to make the regression only on samples possibly being errors (we remove samples with high allelic fraction and run the regression on remaining ones). This was implemented because true variants can biased the regression if present in a high proportion.

To better manage the extra robust regression, we need to control the minimum allelic fraction to exclude a sample at a position in the regression, and also the minimum and maximum proportion of samples having such an allelic fraction, to exclude them all. For that, 3 parameters have to be included:
  * `min_af_extra_robust`
  * `min_prop_extra_robust`
  * `max_prop_extra_robust`

These parameters are already customizable in the regression [here](https://github.com/IARCbioinfo/needlestack/blob/master/bin/glm_rob_nb.r#L18), but they need to be passed to the nextflow script [here](https://github.com/IARCbioinfo/needlestack/blob/gabriela_cpp/needlestack.nf#L468) and [here](https://github.com/IARCbioinfo/needlestack/blob/gabriela_cpp/needlestack.nf#L204), and read by the R script [here](https://github.com/IARCbioinfo/needlestack/blob/gabriela_cpp/needlestack.nf#L468).

Obviously these changes have to be included in the doc!

**Comment by V-Catherine** [comment]
It's done :-)

**Comment by tdelhomme** [comment]
@V-Catherine : The best way is to mention the issue in the commit which fixed it (with `#`), and then ask for a pull request (to merge dev into v1.1b). This will closed the issue and report it in the log file !

**Comment by mfoll** [comment]
@aurelieGabriel could you please add the new parameters to the bash version? (when you come back). See #165
