### ISSUE TITLE
How to identify each sample?

### ISSUE THREAD

**Issue by FerVallejoLec** [IARCbioinfo/needlestack#166]
Hi
I was wondering if I could kwon which variations are in each sample.

Thanks.

**Comment by tdelhomme** [comment]
Hi,

Actually needlestack returns a multi sample [VCF file](https://samtools.github.io/hts-specs/VCFv4.2.pdf), so each line corresponds to a particular mutation and each column to a sample, i.e. to the status of the sample for the mutation (see the `format` field).  

You can filter out the VCF for a particular sample using `bcftools -s`, and after that you can use `bcftools filter` ([manual](https://samtools.github.io/bcftools/bcftools.html)) to filter on the `QVAL` field to keep only mutated positions on this sample. The `QVAL` field corresponds to the "probability" of being mutated.

Do not hesitate to ask if something is still unclear!
