### ISSUE TITLE
Replace the input of a BAM directory with a text file listing BAM to include?

### ISSUE THREAD

**Issue by mfoll** [IARCbioinfo/needlestack#169]
This is an open discussion. Currently the input of BAM files done by giving a directory as an input. The pipeline automatically uses all the BAM in this directory. This is not always very convenient, for example:
- when you want to exclude a particular sample, you need to move it out of the directory. 
- when you want to include BAM files from different directories you need to create a new directory and add symlinks
- when you want to test different scenarios (including different subsets of BAM files) you need to create a directory each time
...

We could instead have an input as a text file listing the BAM files to include. This is already the case when using the Tumor/Normal pair feature. The drawback is that user need to create this file, which can be cumbersome.

Could we have an hybrid approach without having a too complex nextflow code?

**Comment by mfoll** [comment]
What do you think? (users and devs point of view would be both useful)

**Comment by tdelhomme** [comment]
What do you mean by "hybrid approach"? Does it mean allowing both folder and file?

**Comment by mfoll** [comment]
Yes.

**Comment by tdelhomme** [comment]
I think it is not too complex in term of development, we can have only one parameter `input_bams`, and test if it is a file or a folder in groovy ([see this tuto, section Test if File or Directory](http://grails.asia/groovy-file-examples))

**Comment by aurelieGabriel** [comment]
I agree with @tdelhomme.
If the user gives a file in input, then the script will itself create a directory containing the links?

**Comment by tdelhomme** [comment]
Actually no, I think the idea is just to adapt the way nextflow constructs the channel if input bam depending of the type of entry (file or folder).

**Comment by aurelieGabriel** [comment]
:+1:

**Comment by mfoll** [comment]
Maybe add a note here too: https://github.com/IARCbioinfo/needlestack/tree/dev#warning
