### ISSUE TITLE
Add version numbers in VCF output

### ISSUE THREAD

**Issue by mfoll** [IARCbioinfo/needlestack#20]
It would be good to write at least the pipeline version, nextflow version and the docker container version.

**Comment by mfoll** [comment]
The `.nextflow.log`file contains useful informations:
- nextflow version
- pipeline version
- the command line used to launch it (so if a specific docker image is used it's written too)
- I can't find the docker Image ID

Currently only nextflow version number is accessible with `$NXF_VER` (see [here](http://www.nextflow.io/docs/latest/config.html?highlight=environment#environment-variables)).

Could we have more environment variables with these informations @pditommaso (pipeline version, docker image ID, eventually the full command line)?

**Comment by mfoll** [comment]
It could also be useful to obtain the versions of each tool used (in case people don't use docker, and even with docker for easier reference). We could add a process dedicated to that doing:
```bash
perl --version
samtools --version
bedtools --version
Rscript --version
```
And writing all these somewhere in the VCF.
Unfortunately `vcflib` has no option to display its version number at the moment (requested [here](https://github.com/ekg/vcflib/issues/102)).

**Comment by pditommaso** [comment]
It is not clear how do you want these environment variables. Let's continue the discussion in the nextflow mailing list / gitter / github repo.

**Comment by mfoll** [comment]
Linked to #41

**Comment by mfoll** [comment]
See nextflow-io/nextflow#79

**Comment by mfoll** [comment]
Note that it is now also available for vcflib: https://github.com/vcflib/vcflib/issues/102
```
vcfoverlay -v
```
