### ISSUE TITLE
Add on option to give a VCF as an input to only recall variants it contains

### ISSUE THREAD

**Issue by mfoll** [IARCbioinfo/needlestack#46]
In this case the bed file is not needed. The problem will be non-standard notation of variants: they should be left aligned/normalized first with only one ALT allele per line.

**Comment by tdelhomme** [comment]
Option `--input_vcf`, see commit [here] (https://github.com/IARCbioinfo/needlestack/commit/2f9d5df2f61942838a39027190407f93a6c8f6c7)
At the moment only work for GATK vcf as input.
