### ISSUE TITLE
Remove unnecessary intermediate outputs

### ISSUE THREAD

**Issue by mfoll** [IARCbioinfo/needlestack#51]
The only important outputs are: the final VCF and PDF files. All other intermediate files should only be present in nextflow `work` directory. This will imply:
- removing `storeDir` directives in `split_bed`, `samtools_mpileup` and `mpileup2table` processes
- deleting the intermediate VCF outputs at the end of `collect_vcf_result` (see how we delete the empty pdf files).
- renaming the VCF output dir as PDF
- deleting the PDF folder and the `all_variants.vcf` file as the first step in the pipeline

It will has the advantage that the pipeline will be restarted from the beginning by default. We should note in the manual that the output is erased when it exists already. Users will still have the option to resume an interrupted pipeline by adding the `-resume` option to the command line (add that to the manual too).

**Comment by mfoll** [comment]
See nextflow-io/nextflow#81

**Comment by mfoll** [comment]
Now that we use `publishDir`, my 4th point above is no longer necessary as the default behaviour is (https://github.com/nextflow-io/nextflow/blob/master/docs/process.rst#publishdir):
> any existing file in the specified folder will be overridden (default: true during normal pipeline execution and false when pipeline execution is resumed).

**Comment by tdelhomme** [comment]
Yes it's true.
Also I modified the script as you mentionned.
